export default {
  prague: {
    id: 26,
    title: "PRAGUE",
    slug: "prague",
    image: "prague.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  berlin: {
    id: 16,
    title: "BERLIN",
    slug: "berlin",
    image: "berlin.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  paris: {
    id: 73,
    title: "PARIS",
    slug: "paris",
    image: "paris.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  riga: {
    id: 23,
    title: "RIGA",
    slug: "riga",
    image: "riga.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  tallin: {
    id: 1,
    title: "TALLIN",
    slug: "tallin",
    image: "tallin.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  vilnius: {
    id: 6,
    title: "VILNIUS",
    slug: "vilnius",
    image: "vilnius.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  munich: {
    id: 24,
    title: "MUNICH",
    slug: "munich",
    image: "munich.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  vienna: {
    id: 31,
    title: "VIENNA",
    slug: "vienna",
    image: "vienna.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  "new-york": {
    id: 74,
    title: "NEW YORK",
    slug: "new-york",
    image: "new-york.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  abudhabi: {
    id: 83,
    title: "ABU DHABI",
    slug: "abu-dhabi",
    image: "abu-dhabi.jpeg",
  },
  almaty: {
    id: 60,
    title: "Almaty",
    slug: "almaty",
    image: "almaty.jpeg",
  },
  almere: {
    id: 64,
    title: "Almere",
    slug: "almere",
    image: "almere.jpeg",
  },
  amsterdam: {
    id: 15,
    title: "Amsterdam",
    slug: "amsterdam",
    image: "amsterdam.jpeg",
  },
  antalya: {
    id: 84,
    title: "Antalya",
    slug: "antalya",
    image: "antalya.jpeg",
  },
  antwerp: {
    id: 35,
    title: "Antwerp",
    slug: "antwerp",
    image: "antwerp.jpeg",
  },
  athens: {
    id: 85,
    title: "Athens",
    slug: "athens",
    image: "athens.jpeg",
  },
  atlanta: {
    id: 45,
    title: "Atlanta",
    slug: "atlanta",
    image: "atlanta.jpeg",
  },
  auckland: {
    id: 86,
    title: "Auckland",
    slug: "auckland",
    image: "aucland.jpeg",
  },
  bangalore: {
    id: 54,
    title: "Bangalore",
    slug: "bangalore",
    image: "bangalore.jpeg",
  },
  bangkok: {
    id: 87,
    title: "Bangkok",
    slug: "bangkok",
    image: "bangkok.jpeg",
  },
  barcelona: {
    id: 22,
    title: "Barcelona",
    slug: "barcelona",
    image: "barcelona.jpeg",
  },
  basel: {
    id: 36,
    title: "Basel",
    slug: "basel",
    image: "basel.jpeg",
  },
  beijing: {
    id: 88,
    title: "beijing",
    slug: "beijing",
    image: "beijing.jpeg",
  },
  berlin: {
    id: 16,
    title: "Berlin",
    slug: "berlin",
    image: "berlin.jpeg",
  },
  bogota: {
    id: 37,
    title: "Bogota",
    slug: "bogota",
    image: "bogota.jpeg",
  },
  brasov: {
    id: 17,
    title: "Brasov",
    slug: "brasov",
    image: "brasov.jpeg",
  },
  bratislava: {
    id: 89,
    title: "Bratislava",
    slug: "bratislava",
    image: "bratislava.jpeg",
  },
  brussels: {
    id: 76,
    title: "Brussels",
    slug: "brussels",
    image: "brussels.jpeg",
  },
  bucharest: {
    id: 91,
    title: "Bucharest",
    slug: "bucharest",
    image: "bucharest.jpeg",
  },
  budapest: {
    id: 30,
    title: "Budapest",
    slug: "budapest",
    image: "budapest.jpeg",
  },
  "buenos-aires": {
    id: 92,
    title: "Buenos Aires",
    slug: "buenos-aires",
    image: "buenos-aires.jpeg",
  },
  burgas: {
    id: 93,
    title: "Burgas",
    slug: "burgas",
    image: "burgas.jpeg",
  },
  "byron-bay": {
    id: 47,
    title: "Byron Bay",
    slug: "byron-bay",
    image: "byron-bay.jpeg",
  },
  cairo: {
    id: 94,
    title: "Cairo",
    slug: "cairo",
    image: "cairo.jpeg",
  },
  cancun: {
    id: 95,
    title: "Cancun",
    slug: "cancun",
    image: "cancun.jpeg",
  },
  "cape-town": {
    id: 96,
    title: "Cape Town",
    slug: "cape-town",
    image: "cape-town.jpeg",
  },
  caracas: {
    id: 21,
    title: "Caracas",
    slug: "caracas",
    image: "caracas.jpeg",
  },
  cartagena: {
    id: 38,
    title: "Cartagena",
    slug: "cartagena",
    image: "cartagena.jpeg",
  },
  cartago: {
    id: 27,
    title: "Cartago",
    slug: "cartago",
    image: "cartago.jpeg",
  },
  chicago: {
    id: 97,
    title: "Chicago",
    slug: "chicago",
    image: "chicago.jpeg",
  },
  christchurch: {
    id: 98,
    title: "Christchurch",
    slug: "christchurch",
    image: "christchurch.jpeg",
  },
  "cluj-napoca": {
    id: 61,
    title: "Cluj Napoca",
    slug: "cluj-napoca",
    image: "cluj-napoca.jpeg",
  },
  cologne: {
    id: 39,
    title: "Cologne",
    slug: "cologne",
    image: "cologne.jpeg",
  },
  copenhagen: {
    id: 19,
    title: "Copenhagen",
    slug: "copenhagen",
    image: "copenhagen.jpeg",
  },
  damascus: {
    id: 99,
    title: "Damascus",
    slug: "damascus",
    image: "damascus.jpeg",
  },
  delhi: {
    id: 100,
    title: "Delhi",
    slug: "delhi",
    image: "delhi.jpeg",
  },
  denpasar: {
    id: 101,
    title: "Denpasar",
    slug: "denpasar",
    image: "denpasar.jpeg",
  },
  dubai: {
    id: 102,
    title: "Dubai",
    slug: "dubai",
    image: "dubai.jpeg",
  },
  dublin: {
    id: 14,
    title: "Dublin",
    slug: "dublin",
    image: "dublin.jpeg",
  },
  edinburgh: {
    id: 63,
    title: "Edinburgh",
    slug: "edinburgh",
    image: "edinburgh.jpeg",
  },
  eindhoven: {
    id: 68,
    title: "Eindhoven",
    slug: "eindhoven",
    image: "eindhoven.jpeg",
  },
  fez: {
    id: 40,
    title: "Fez",
    slug: "fez",
    image: "fez.jpeg",
  },
  frankfurt: {
    id: 7,
    title: "Frankfurt",
    slug: "frankfurt",
    image: "frankfurt.jpeg",
  },
  gdansk: {
    id: 65,
    title: "Gdansk",
    slug: "gdansk",
    image: "gdansk.jpeg",
  },
  geneva: {
    id: 46,
    title: "Geneva",
    slug: "geneva",
    image: "geneva.jpeg",
  },
  hamburg: {
    id: 49,
    title: "Hamburg",
    slug: "hamburg",
    image: "hamburg.jpeg",
  },
  helsinki: {
    id: 5,
    title: "Helsinki",
    slug: "helsinki",
    image: "helsinki.jpeg",
  },
  "ibiza-town": {
    id: 66,
    title: "Ibiza Town",
    slug: "ibiza-town",
    image: "ibiza-town.jpeg",
  },
  kaasan: {
    id: 53,
    title: "Kaasan",
    slug: "kaasan",
    image: "kaasan.jpg",
  },
  kaunas: {
    id: 9,
    title: "Kaunas",
    slug: "kaunas",
    image: "kaunas.jpeg",
  },
  krakow: {
    id: 32,
    title: "Krakow",
    slug: "krakow",
    image: "krakow.jpg",
  },
  "las-palmas": {
    id: 80,
    title: "Las Palmas",
    slug: "las-palmas",
    image: "las-palmas.jpeg",
  },
  lisbon: {
    id: 10,
    title: "Lisbon",
    slug: "lisbon",
    image: "lisbon.jpeg",
  },
  london: {
    id: 48,
    title: "London",
    slug: "london",
    image: "london.jpeg",
  },
  "los-angeles": {
    id: 33,
    title: "Los Angeles",
    slug: "los-angeles",
    image: "los-angeles.jpeg",
  },
  lund: {
    id: 59,
    title: "Lund",
    slug: "lund",
    image: "lund.jpeg",
  },
  malaga: {
    id: 34,
    title: "Malaga",
    slug: "malaga",
    image: "malaga.jpeg",
  },
  manchester: {
    id: 82,
    title: "Manchester",
    slug: "manchester",
    image: "manchester.jpeg",
  },
  marseille: {
    id: 41,
    title: "Marseille",
    slug: "marseille",
    image: "marseille.jpeg",
  },
  medellin: {
    id: 42,
    title: "Medellin",
    slug: "medellin",
    image: "medellin.jpeg",
  },
  melbourne: {
    id: 25,
    title: "Melbourne",
    slug: "melbourne",
    image: "melbourne.jpeg",
  },
  milan: {
    id: 78,
    title: "Milan",
    slug: "milan",
    image: "milan.jpeg",
  },
  minsk: {
    id: 52,
    title: "Minsk",
    slug: "minsk",
    image: "hminsk.jpeg",
  },
  moscow: {
    id: 77,
    title: "Moscow",
    slug: "moscow",
    image: "moscow.jpeg",
  },
  munich: {
    id: 74,
    title: "Munich",
    slug: "munich",
    image: "munich.jpeg",
  },
  narva: {
    id: 58,
    title: "Narva",
    slug: "narva",
    image: "narva.jpeg",
  },
  "new-york": {
    id: 74,
    title: "New York",
    slug: "new-york",
    image: "new-york.jpeg",
  },
  paraiso: {
    id: 28,
    title: "Paraiso",
    slug: "paraiso",
    image: "paraiso-jpeg",
  },
  "playa-del-ingles": {
    id: 81,
    title: "Playa del Inglés",
    slug: "playa-del-ingles",
    image: "playa-del-ingles.jpeg",
  },
  pokhara: {
    id: 43,
    title: "Pokhara",
    slug: "pokhara",
    image: "pokhara.jpeg",
  },
  porto: {
    id: 44,
    title: "Porto",
    slug: "porto",
    image: "porto.jpeg",
  },
  parnu: {
    id: 4,
    title: "Pärnu",
    slug: "parnu",
    image: "parnu.jpeg",
  },
  riga: {
    id: 23,
    title: "Riga",
    slug: "riga",
    image: "riga.jpeg",
  },
  "rio-de-janeiro": {
    id: 8,
    title: "Rio de Janeiro",
    slug: "rio-de-janeiro",
    image: "rio-de-janeiro.jpeg",
  },
  rome: {
    id: 75,
    title: "Rome",
    slug: "rome",
    image: "rome.jpeg",
  },
  rotterdam: {
    id: 13,
    title: "Rotterdam",
    slug: "rotterdam",
    image: "rotterdam.jpeg",
  },
  "san-francisco": {
    id: 11,
    title: "San Francisco",
    slug: "san-francisco",
    image: "san-francisko.jpeg",
  },
  "san-jose": {
    id: 20,
    title: "San Josee",
    slug: "san-jose",
    image: "san-jose.jpeg",
  },
  sana: {
    id: 79,
    title: "Sana'a",
    slug: "sana",
    image: "sana.jpeg",
  },
  seoul: {
    id: 72,
    title: "Seoul",
    slug: "seoul",
    image: "seoul.jpeg",
  },
  siegen: {
    id: 56,
    title: "Siegen",
    slug: "siegen",
    image: "siegen.jpeg",
  },
  "st-petersburg": {
    id: 67,
    title: "St Petersburg",
    slug: "st-petersburg",
    image: "st-petersburg.jpeg",
  },
  stockholm: {
    id: 57,
    title: "Stockholm",
    slug: "stockholm",
    image: "stockholm.jpeg",
  },
  saopaulo: {
    id: 12,
    title: "Sao Paulo",
    slug: "saopaulo",
    image: "sao-paulo.jpeg",
  },
  tallinn: {
    id: 74,
    title: "Tallinn",
    slug: "tallinn",
    image: "tallinn.jpeg",
  },
  tartu: {
    id: 3,
    title: "Tartu",
    slug: "tartu",
    image: "tartu.jpeg",
  },
  tbilisi: {
    id: 62,
    title: "Tbilisi",
    slug: "tbilisi",
    image: "tbilisi.jpeg",
  },
  thessaloniki: {
    id: 55,
    title: "Thessaloniki",
    slug: "thessaloniki",
    image: "thessaloniki.jpeg",
  },
  tokyo: {
    id: 29,
    title: "Tokyo",
    slug: "tokyo",
    image: "tokyo.jpeg",
  },
  turin: {
    id: 70,
    title: "Turin",
    slug: "Turin",
    image: "turin.jpeg",
  },
  utrecht: {
    id: 69,
    title: "Utrecht",
    slug: "utrecht",
    image: "utrecht.jpeg",
  },
  vancouver: {
    id: 51,
    title: "Vancouver",
    slug: "vancouver",
    image: "vancouver.jpeg",
  },
  vienna: {
    id: 31,
    title: "Vienna",
    slug: "vienna",
    image: "vienna.jpeg",
  },
  vilnius: {
    id: 6,
    title: "Vilnius",
    slug: "vilnius",
    image: "vilnius.jpeg",
  },
  warsaw: {
    id: 18,
    title: "Warsaw",
    slug: "warsaw",
    image: "warsaw.jpeg",
  },
  "washington-dc": {
    id: 50,
    title: "Washington DC",
    slug: "washington-dc",
    image: "washington-dc.jpeg",
  },
  wroclaw: {
    id: 71,
    title: "Wroclaw",
    slug: "wroclaw",
    image: "wroclaw.jpeg",
  },
};
