export default [
  {
    id: 26,
    title: "PRAGUE",
    slug: "prague",
    image: "prague.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  {
    id: 16,
    title: "BERLIN",
    slug: "berlin",
    image: "berlin.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  {
    id: 73,
    title: "PARIS",
    slug: "paris",
    image: "paris.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  {
    id: 23,
    title: "RIGA",
    slug: "riga",
    image: "riga.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  {
    id: 1,
    title: "TALLIN",
    slug: "tallin",
    image: "tallinn.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  {
    id: 6,
    title: "VILNIUS",
    slug: "vilnius",
    image: "vilnius.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  {
    id: 24,
    title: "MUNICH",
    slug: "munich",
    image: "munich.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  {
    id: 31,
    title: "VIENNA",
    slug: "vienna",
    image: "vienna.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
  {
    id: 74,
    title: "NEW YORK",
    slug: "new-york",
    image: "new-york.jpeg",
    description: "369 tips and 65 tours by 90 locals",
  },
];
